# Generated by Django 6.0.3 on 2026-08-17 12:45

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
from django.contrib.postgres.operations import TrigramExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lambda_tasks", "0002_alter_taskrecord_status"),
    ]

    operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name="taskrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.comparison.Cast(
                        "kwargs", output_field=models.TextField()
                    ),
                    name="gin_trgm_ops",
                ),
                name="taskrecord_kwargs_trgm",
            ),
        ),
    ]
