# Generated by Django 6.0.3 on 2026-08-18 09:47

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lambda_tasks", "0003_taskrecord_taskrecord_kwargs_trgm"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="taskrecord",
            name="taskrecord_kwargs_trgm",
        ),
        migrations.AddIndex(
            model_name="taskrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.comparison.Cast(
                            "id", output_field=models.TextField()
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="taskrecord_id_trgm",
            ),
        ),
        migrations.AddIndex(
            model_name="taskrecord",
            index=django.contrib.postgres.indexes.GinIndex(
                django.contrib.postgres.indexes.OpClass(
                    django.db.models.functions.text.Upper(
                        django.db.models.functions.comparison.Cast(
                            "kwargs", output_field=models.TextField()
                        )
                    ),
                    name="gin_trgm_ops",
                ),
                name="taskrecord_kwargs_trgm",
            ),
        ),
    ]
